# Node.js 이미지를 기반으로 함
FROM node:18.19.1-alpine

# 작업 디렉토리 설정
WORKDIR /usr/src/app

# package.json과 yarn.lock 파일 복사
COPY package.json ./
COPY yarn.lock ./

# 의존성 설치
RUN yarn

# 필요한 모든 파일 복사
COPY . .

# Next.js 앱 빌드
RUN yarn build

# 컨테이너 포트 3000 설정
EXPOSE 3000

# 애플리케이션 실행
CMD ["yarn", "start"]
